version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./react_app:/usr/src/app # ローカルをコンテナ内にマウント
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    stdin_open: true 
  
  backend:
    build: ./backend
    command: ["yarn", "start"]
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads